<a href="https://colab.research.google.com/github/khalandarsihan/PyTorch/blob/main/code_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

In [2]:
np.random.rand(3, 4)

array([[0.55480831, 0.93192719, 0.43785626, 0.58816862],
       [0.52624461, 0.47907896, 0.44442792, 0.42719909],
       [0.89015979, 0.93061644, 0.14709071, 0.55587797]])

In [3]:
tensor_2d = torch.rand(3, 4)
tensor_2d

tensor([[0.6954, 0.2894, 0.6306, 0.5462],
        [0.7291, 0.7930, 0.9684, 0.0799],
        [0.2694, 0.4489, 0.3039, 0.4373]])

In [4]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [5]:
torch.tensor(np.random.rand(3, 4))

tensor([[0.1703, 0.7522, 0.1515, 0.9352],
        [0.5272, 0.9237, 0.2749, 0.4154],
        [0.8763, 0.6015, 0.2331, 0.2242]], dtype=torch.float64)

In [7]:
t=torch.arange(10)

In [8]:
t.reshape(5,2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [9]:
t.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [31]:
t.reshape(10,1)

tensor([[   0],
        [   1],
        [   2],
        [   3],
        [   4],
        [9999],
        [   6],
        [   7],
        [   8],
        [   9]])

In [30]:
t.reshape(1,10)

tensor([[   0,    1,    2,    3,    4, 9999,    6,    7,    8,    9]])

In [32]:
s = torch.rand(3, 4)
s

tensor([[0.5955, 0.9905, 0.9041, 0.5433],
        [0.0594, 0.7466, 0.0817, 0.0852],
        [0.1923, 0.7710, 0.8971, 0.9903]])

In [33]:
s[1,1] = 0

In [34]:
s

tensor([[0.5955, 0.9905, 0.9041, 0.5433],
        [0.0594, 0.0000, 0.0817, 0.0852],
        [0.1923, 0.7710, 0.8971, 0.9903]])

In [35]:
s1 = s.reshape(2, 6)
s1

tensor([[0.5955, 0.9905, 0.9041, 0.5433, 0.0594, 0.0000],
        [0.0817, 0.0852, 0.1923, 0.7710, 0.8971, 0.9903]])

In [36]:
s1[0, 2] = 9999

In [37]:
s1

tensor([[5.9553e-01, 9.9047e-01, 9.9990e+03, 5.4331e-01, 5.9419e-02, 0.0000e+00],
        [8.1659e-02, 8.5187e-02, 1.9228e-01, 7.7100e-01, 8.9708e-01, 9.9034e-01]])

In [38]:
s

tensor([[5.9553e-01, 9.9047e-01, 9.9990e+03, 5.4331e-01],
        [5.9419e-02, 0.0000e+00, 8.1659e-02, 8.5187e-02],
        [1.9228e-01, 7.7100e-01, 8.9708e-01, 9.9034e-01]])

In [39]:
a = torch.arange(10)

In [43]:
a = torch.arange(10)
b = a.reshape(5, 2)

In [44]:
b

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [45]:
b[:,1]

tensor([1, 3, 5, 7, 9])

In [46]:
b[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])